server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"
      - "prod"


build:
  version: "3.0"


accounts:
  message: "Hello from accounts service"
  contactDetails:
    name: "John Doe"
    email: "johndoe@gmail.com"
  onCallSupport:
    - (800) 123-4567
    - (800) 765-4321

