spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
            uri: "https://github.com/eazybytes/eazybytes-config.git"
            default-label: main
            timeout: 5
            clone-on-start: true
            force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
    key: "EF1hH1TuiOrHUqeCc71UHg20zn8KmmbT"

server:
  port: 8071
